// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXan4DaEN_cdJlOB-xEYxGorPiTNsEUVA',
    appId: '1:568450203907:web:74170b788683de01fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    authDomain: 'dossier-a8fe7.firebaseapp.com',
    databaseURL: 'https://dossier-a8fe7-default-rtdb.firebaseio.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
    measurementId: 'G-0EHEXZMPPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgIMq88WSqBOpcmgFZbSgjBe9xUx-7jWk',
    appId: '1:568450203907:android:43433544607394f5fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    databaseURL: 'https://dossier-a8fe7-default-rtdb.firebaseio.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLhc1zvpaNRCscIrRO67iPLC8ba2E-CCk',
    appId: '1:568450203907:ios:58f00169bb6254f1fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    databaseURL: 'https://dossier-a8fe7-default-rtdb.firebaseio.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
    iosClientId: '568450203907-c3cr8a49ifnu9pm0g2g542sq21m1eks3.apps.googleusercontent.com',
    iosBundleId: 'com.malcolm.dossier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLhc1zvpaNRCscIrRO67iPLC8ba2E-CCk',
    appId: '1:568450203907:ios:58f00169bb6254f1fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    databaseURL: 'https://dossier-a8fe7-default-rtdb.firebaseio.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
    iosClientId: '568450203907-c3cr8a49ifnu9pm0g2g542sq21m1eks3.apps.googleusercontent.com',
    iosBundleId: 'com.malcolm.dossier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXan4DaEN_cdJlOB-xEYxGorPiTNsEUVA',
    appId: '1:568450203907:web:0ac653f390c9f3eafba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    authDomain: 'dossier-a8fe7.firebaseapp.com',
    databaseURL: 'https://dossier-a8fe7-default-rtdb.firebaseio.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
    measurementId: 'G-4JYM1J762H',
  );

}