// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLp3YjEdMfI_r2JkcCj7UzhLI1bR80I0',
    appId: '1:568450203907:web:346ebdd5bc892cf7fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    authDomain: 'dossier-a8fe7.firebaseapp.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
    measurementId: 'G-6JCM9D1BYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgIMq88WSqBOpcmgFZbSgjBe9xUx-7jWk',
    appId: '1:568450203907:android:24a1400f29de7a7bfba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    storageBucket: 'dossier-a8fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLhc1zvpaNRCscIrRO67iPLC8ba2E-CCk',
    appId: '1:568450203907:ios:861174aa67d25098fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    storageBucket: 'dossier-a8fe7.appspot.com',
    iosBundleId: 'com.malcolm.dossier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLhc1zvpaNRCscIrRO67iPLC8ba2E-CCk',
    appId: '1:568450203907:ios:861174aa67d25098fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    storageBucket: 'dossier-a8fe7.appspot.com',
    iosBundleId: 'com.malcolm.dossier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFLp3YjEdMfI_r2JkcCj7UzhLI1bR80I0',
    appId: '1:568450203907:web:52f2057eda0075f1fba936',
    messagingSenderId: '568450203907',
    projectId: 'dossier-a8fe7',
    authDomain: 'dossier-a8fe7.firebaseapp.com',
    storageBucket: 'dossier-a8fe7.appspot.com',
    measurementId: 'G-H055566373',
  );
}
